[package]
name = "hyperion"
version = "0.1.0"
description = "A multiplatform Matrix client"
authors = ["VinVel <dev+hyperion@velcore.net>"]
edition = "2024"
license = "AGPL-3.0-only"
repository = "https://github.com/VinVel/Hyperion"
homepage = "https://hyperion.velcore.net"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "hyperion_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { workspace = true, features = [] }

[dependencies]
tauri = { workspace = true, features = ["unstable"] }
tauri-plugin-opener = { workspace = true }
tauri-plugin-dialog = { workspace = true }
tauri-plugin-fs = { workspace = true }
tauri-plugin-i18n = { workspace = true }
tauri-plugin-os = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
base64 = { workspace = true }
rand = { workspace = true }
rusqlite = { workspace = true, features = ["bundled"] }
reqwest = { workspace = true, features = ["json"] }
rust-i18n = { workspace = true }
futures-util = { workspace = true }
eyeball-im = { workspace = true }
matrix-sdk-crypto = { workspace = true }
keyring-core = { workspace = true }

[dependencies.matrix-sdk]
workspace = true
features = [
    "e2e-encryption", 
    "automatic-room-key-forwarding", 
    "bundled-sqlite", 
    "experimental-search",
]

[dependencies.matrix-sdk-ui]
workspace = true
features = [
    "unstable-msc4274"
]

[target.'cfg(target_os = "android")'.dependencies]
android-native-keyring-store = { workspace = true }
ndk-context = { workspace = true }
rustls = { workspace = true }
rustls-native-certs = { workspace = true }
tauri-plugin-app-events = { workspace = true }
tauri-plugin-mobile-webview-overlay = { workspace = true }
webpki-roots = { workspace = true }

[target.'cfg(target_os = "ios")'.dependencies]
apple-native-keyring-store = { workspace = true, features = ["protected"] }
tauri-plugin-app-events = { workspace = true }
tauri-plugin-mobile-webview-overlay = { workspace = true }

[target.'cfg(target_os = "windows")'.dependencies]
windows-native-keyring-store = { workspace = true }

[target.'cfg(target_os = "macos")'.dependencies]
apple-native-keyring-store = { workspace = true, features = ["keychain"] }

[target.'cfg(target_os = "linux")'.dependencies]
linux-keyutils-keyring-store = { workspace = true }
