[workspace]
members = [
    "src-tauri", 
    "plugins/*"
    ]
resolver = "3"

[workspace.dependencies]
tauri-plugin-mobile-webview-overlay = { path = "plugins/tauri-plugin-mobile-webview-overlay" }
tauri-plugin-app-events = { path = "plugins/tauri-plugin-app-events"}

[profile.dev]
debug = true

[profile.dev.package."*"]
debug = false
strip = true

[profile.release]
strip = true
opt-level = "s"
lto = true
codegen-units = 1
