[build.env]
passthrough = [
  "PKG_CONFIG_ALLOW_CROSS",
  "PKG_CONFIG_SYSROOT_DIR",
  "TARGET_PKG_CONFIG_ALLOW_CROSS",
  "TARGET_PKG_CONFIG_SYSROOT_DIR",
  "PKG_CONFIG_ALLOW_CROSS_riscv64gc_unknown_linux_gnu",
  "PKG_CONFIG_SYSROOT_DIR_riscv64gc_unknown_linux_gnu",
]

[target.riscv64gc-unknown-linux-gnu]
dockerfile = "../.github/cross/Dockerfile.riscv64-gnu"
