[target.'cfg(target_os = "linux")']
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=mold"]   

[target.'cfg(target_os = "macos")']
linker = "clang"
rustflags = ["-C", "link-arg=--ld-path=/usr/local/bin/ld64.mold"]

[target.'cfg(target_os = "windows")']
linker = "clang"