<#
Copyright (c) 2026 VinVel

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, version 3 only.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.

Project home: hyperion.velcore.net
#>

param(
  [switch]$Ci
)

$ErrorActionPreference = 'Stop'

function Normalize-Path([string]$Value) {
  return ($Value.Trim() -replace '\\', '/')
}

function Read-RequiredValue([string]$Name, [string]$Default = '') {
  $value = $Default

  if (-not $Ci) {
    $prompt = if ($Default) { "$Name [$Default]" } else { $Name }
    $raw = Read-Host $prompt
    $value = if ([string]::IsNullOrWhiteSpace($raw)) { $Default } else { $raw }
  }

  if ([string]::IsNullOrWhiteSpace($value)) {
    throw "$Name is required."
  }

  return (Normalize-Path $value)
}

function Read-MinSdk([string]$Default = '24') {
  $value = $Default

  if (-not $Ci) {
    $raw = Read-Host "ANDROID_MIN_SDK [$Default]"
    $value = if ([string]::IsNullOrWhiteSpace($raw)) { $Default } else { $raw.Trim() }
  }

  if ($value -notmatch '^[0-9]+$') {
    throw 'ANDROID_MIN_SDK must be a positive integer.'
  }

  return $value
}

function Get-HighestNdkHome([string]$AndroidHome) {
  if ([string]::IsNullOrWhiteSpace($AndroidHome)) {
    return ''
  }

  $androidHomeWin = $AndroidHome -replace '/', '\'
  $ndkRoot = Join-Path $androidHomeWin 'ndk'
  if (-not (Test-Path $ndkRoot)) {
    return ''
  }

  $candidate = Get-ChildItem -Path $ndkRoot -Directory -ErrorAction SilentlyContinue |
    Where-Object { $_.Name -match '^\d+(\.\d+)*$' } |
    Sort-Object { [version]$_.Name } -Descending |
    Select-Object -First 1

  if ($null -eq $candidate) {
    return ''
  }

  return (Normalize-Path $candidate.FullName)
}

function Write-File([string]$Path, [string]$Content) {
  $parent = Split-Path -Parent $Path
  if (-not [string]::IsNullOrWhiteSpace($parent) -and -not (Test-Path $parent)) {
    New-Item -ItemType Directory -Path $parent -Force | Out-Null
  }

  Set-Content -Path $Path -Value $Content -NoNewline
}

Write-Host 'Android toolchain config generator'
if (-not $Ci) {
  Write-Host 'Press Enter to accept defaults.'
}

$defaultAndroidHome = if ($env:ANDROID_HOME) { $env:ANDROID_HOME } else { '' }
$ANDROID_HOME = Read-RequiredValue 'ANDROID_HOME' $defaultAndroidHome

$detectedNdkHome = Get-HighestNdkHome $ANDROID_HOME
if ($detectedNdkHome) {
  Write-Host "Detected latest NDK: $detectedNdkHome"
}

$defaultNdkHome = if ($env:NDK_HOME) { $env:NDK_HOME } elseif ($env:ANDROID_NDK_HOME) { $env:ANDROID_NDK_HOME } elseif ($detectedNdkHome) { $detectedNdkHome } else { '' }
$NDK_HOME = Read-RequiredValue 'NDK_HOME' $defaultNdkHome

$defaultMinSdk = if ($env:ANDROID_MIN_SDK) { $env:ANDROID_MIN_SDK } else { '24' }
$ANDROID_MIN_SDK = Read-MinSdk $defaultMinSdk

$repoRoot = Resolve-Path (Join-Path $PSScriptRoot '..')
$cargoConfigPath = Join-Path $repoRoot '.cargo/config.toml'
$localPropertiesPath = Join-Path $repoRoot 'src-tauri/gen/android/local.properties'

$ndkBinPath = Normalize-Path (Join-Path ($NDK_HOME -replace '/', '\') 'toolchains\llvm\prebuilt\windows-x86_64\bin')
if (-not (Test-Path ($ndkBinPath -replace '/', '\'))) {
  throw "NDK toolchain bin directory not found: $ndkBinPath"
}

$cargoConfig = @"
# This file is autogenerated by scripts/generate-android-env.ps1.
# It contains host-specific Android SDK/NDK paths and must not be committed.

[target.aarch64-linux-android]
linker = "$ndkBinPath/aarch64-linux-android$ANDROID_MIN_SDK-clang.cmd"

[target.armv7-linux-androideabi]
linker = "$ndkBinPath/armv7a-linux-androideabi$ANDROID_MIN_SDK-clang.cmd"

[target.i686-linux-android]
linker = "$ndkBinPath/i686-linux-android$ANDROID_MIN_SDK-clang.cmd"

[target.x86_64-linux-android]
linker = "$ndkBinPath/x86_64-linux-android$ANDROID_MIN_SDK-clang.cmd"

[env]
ANDROID_HOME = { value = "$ANDROID_HOME", force = true }
NDK_HOME = { value = "$NDK_HOME", force = true }
ANDROID_NDK_HOME = { value = "$NDK_HOME", force = true }
ANDROID_MIN_SDK = { value = "$ANDROID_MIN_SDK", force = true }

CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER = { value = "$ndkBinPath/aarch64-linux-android$ANDROID_MIN_SDK-clang.cmd", force = true }
CARGO_TARGET_AARCH64_LINUX_ANDROID_AR = { value = "$ndkBinPath/llvm-ar.exe", force = true }

CARGO_TARGET_ARMV7_LINUX_ANDROIDEABI_LINKER = { value = "$ndkBinPath/armv7a-linux-androideabi$ANDROID_MIN_SDK-clang.cmd", force = true }
CARGO_TARGET_ARMV7_LINUX_ANDROIDEABI_AR = { value = "$ndkBinPath/llvm-ar.exe", force = true }

CARGO_TARGET_I686_LINUX_ANDROID_LINKER = { value = "$ndkBinPath/i686-linux-android$ANDROID_MIN_SDK-clang.cmd", force = true }
CARGO_TARGET_I686_LINUX_ANDROID_AR = { value = "$ndkBinPath/llvm-ar.exe", force = true }

CARGO_TARGET_X86_64_LINUX_ANDROID_LINKER = { value = "$ndkBinPath/x86_64-linux-android$ANDROID_MIN_SDK-clang.cmd", force = true }
CARGO_TARGET_X86_64_LINUX_ANDROID_AR = { value = "$ndkBinPath/llvm-ar.exe", force = true }

CC_aarch64_linux_android = { value = "$ndkBinPath/aarch64-linux-android$ANDROID_MIN_SDK-clang.cmd", force = true }
CXX_aarch64_linux_android = { value = "$ndkBinPath/aarch64-linux-android$ANDROID_MIN_SDK-clang++.cmd", force = true }
AR_aarch64_linux_android = { value = "$ndkBinPath/llvm-ar.exe", force = true }

CC_armv7_linux_androideabi = { value = "$ndkBinPath/armv7a-linux-androideabi$ANDROID_MIN_SDK-clang.cmd", force = true }
CXX_armv7_linux_androideabi = { value = "$ndkBinPath/armv7a-linux-androideabi$ANDROID_MIN_SDK-clang++.cmd", force = true }
AR_armv7_linux_androideabi = { value = "$ndkBinPath/llvm-ar.exe", force = true }

CC_i686_linux_android = { value = "$ndkBinPath/i686-linux-android$ANDROID_MIN_SDK-clang.cmd", force = true }
CXX_i686_linux_android = { value = "$ndkBinPath/i686-linux-android$ANDROID_MIN_SDK-clang++.cmd", force = true }
AR_i686_linux_android = { value = "$ndkBinPath/llvm-ar.exe", force = true }

CC_x86_64_linux_android = { value = "$ndkBinPath/x86_64-linux-android$ANDROID_MIN_SDK-clang.cmd", force = true }
CXX_x86_64_linux_android = { value = "$ndkBinPath/x86_64-linux-android$ANDROID_MIN_SDK-clang++.cmd", force = true }
AR_x86_64_linux_android = { value = "$ndkBinPath/llvm-ar.exe", force = true }
"@

$localProperties = @"
## This file is autogenerated by scripts/generate-android-env.ps1.
# It is local to the machine and must not be committed.
sdk.dir=$ANDROID_HOME
"@

Write-File $cargoConfigPath $cargoConfig
Write-File $localPropertiesPath $localProperties

Write-Host "Generated $cargoConfigPath"
Write-Host "Generated $localPropertiesPath"

$legacyEnvPath = Join-Path $repoRoot '.android-env'
if (Test-Path $legacyEnvPath) {
  Write-Host "Legacy file still present and unused by the current setup: $legacyEnvPath"
}
