#!/usr/bin/env bash

# Copyright (c) 2026 VinVel
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, version 3 only.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#
# Project home: hyperion.velcore.net

set -euo pipefail

ci_mode=0
if [[ "${1:-}" == "--ci" ]]; then
  ci_mode=1
  shift
fi

if [[ $# -ne 0 ]]; then
  echo "Usage: $0 [--ci]" >&2
  exit 1
fi

prompt_required() {
  local var_name="$1"
  local default_value="$2"
  local input_value="$default_value"

  if [[ $ci_mode -eq 0 ]]; then
    if [[ -n "$default_value" ]]; then
      read -r -p "$var_name [$default_value]: " input_value
      input_value="${input_value:-$default_value}"
    else
      read -r -p "$var_name: " input_value
    fi
  fi

  input_value="${input_value//\\//}"

  if [[ -z "$input_value" ]]; then
    echo "$var_name is required." >&2
    exit 1
  fi

  printf -v "$var_name" '%s' "$input_value"
}

prompt_min_sdk() {
  local default_value="$1"
  local input_value="$default_value"

  if [[ $ci_mode -eq 0 ]]; then
    read -r -p "ANDROID_MIN_SDK [$default_value]: " input_value
    input_value="${input_value:-$default_value}"
  fi

  if [[ ! "$input_value" =~ ^[0-9]+$ ]]; then
    echo "ANDROID_MIN_SDK must be a positive integer." >&2
    exit 1
  fi

  ANDROID_MIN_SDK="$input_value"
}

detect_latest_ndk_home() {
  local android_home="$1"
  local ndk_root
  ndk_root="${android_home//\\//}/ndk"

  if [[ ! -d "$ndk_root" ]]; then
    echo ""
    return
  fi

  local versions=()
  while IFS= read -r version_dir; do
    versions+=("$version_dir")
  done < <(
    find "$ndk_root" -mindepth 1 -maxdepth 1 -type d -printf '%f\n' \
      | grep -E '^[0-9]+([.][0-9]+)*$' \
      | sort -V
  )

  if [[ ${#versions[@]} -eq 0 ]]; then
    echo ""
    return
  fi

  local latest="${versions[${#versions[@]}-1]}"
  echo "$ndk_root/$latest"
}

echo "Android toolchain config generator"
if [[ $ci_mode -eq 0 ]]; then
  echo "Press Enter to accept defaults."
fi

default_android_home="${ANDROID_HOME:-}"
prompt_required ANDROID_HOME "$default_android_home"

detected_ndk_home="$(detect_latest_ndk_home "$ANDROID_HOME")"
if [[ -n "$detected_ndk_home" ]]; then
  echo "Detected latest NDK: $detected_ndk_home"
fi

default_ndk_home="${NDK_HOME:-${ANDROID_NDK_HOME:-$detected_ndk_home}}"
prompt_required NDK_HOME "$default_ndk_home"

prompt_min_sdk "${ANDROID_MIN_SDK:-24}"

repo_root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
cargo_dir="$repo_root/.cargo"
cargo_config_path="$cargo_dir/config.toml"
local_properties_path="$repo_root/src-tauri/gen/android/local.properties"
ndk_bin_path="$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin"

if [[ ! -d "$ndk_bin_path" ]]; then
  echo "NDK toolchain bin directory not found: $ndk_bin_path" >&2
  exit 1
fi

mkdir -p "$cargo_dir"
mkdir -p "$(dirname "$local_properties_path")"

cat > "$cargo_config_path" <<EOF
# This file is autogenerated by scripts/generate-android-env.sh.
# It contains host-specific Android SDK/NDK paths and must not be committed.

[target.aarch64-linux-android]
linker = "$ndk_bin_path/aarch64-linux-android$ANDROID_MIN_SDK-clang"

[target.armv7-linux-androideabi]
linker = "$ndk_bin_path/armv7a-linux-androideabi$ANDROID_MIN_SDK-clang"

[target.i686-linux-android]
linker = "$ndk_bin_path/i686-linux-android$ANDROID_MIN_SDK-clang"

[target.x86_64-linux-android]
linker = "$ndk_bin_path/x86_64-linux-android$ANDROID_MIN_SDK-clang"

[env]
ANDROID_HOME = { value = "$ANDROID_HOME", force = true }
NDK_HOME = { value = "$NDK_HOME", force = true }
ANDROID_NDK_HOME = { value = "$NDK_HOME", force = true }
ANDROID_MIN_SDK = { value = "$ANDROID_MIN_SDK", force = true }

CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER = { value = "$ndk_bin_path/aarch64-linux-android$ANDROID_MIN_SDK-clang", force = true }
CARGO_TARGET_AARCH64_LINUX_ANDROID_AR = { value = "$ndk_bin_path/llvm-ar", force = true }

CARGO_TARGET_ARMV7_LINUX_ANDROIDEABI_LINKER = { value = "$ndk_bin_path/armv7a-linux-androideabi$ANDROID_MIN_SDK-clang", force = true }
CARGO_TARGET_ARMV7_LINUX_ANDROIDEABI_AR = { value = "$ndk_bin_path/llvm-ar", force = true }

CARGO_TARGET_I686_LINUX_ANDROID_LINKER = { value = "$ndk_bin_path/i686-linux-android$ANDROID_MIN_SDK-clang", force = true }
CARGO_TARGET_I686_LINUX_ANDROID_AR = { value = "$ndk_bin_path/llvm-ar", force = true }

CARGO_TARGET_X86_64_LINUX_ANDROID_LINKER = { value = "$ndk_bin_path/x86_64-linux-android$ANDROID_MIN_SDK-clang", force = true }
CARGO_TARGET_X86_64_LINUX_ANDROID_AR = { value = "$ndk_bin_path/llvm-ar", force = true }

CC_aarch64_linux_android = { value = "$ndk_bin_path/aarch64-linux-android$ANDROID_MIN_SDK-clang", force = true }
CXX_aarch64_linux_android = { value = "$ndk_bin_path/aarch64-linux-android$ANDROID_MIN_SDK-clang++", force = true }
AR_aarch64_linux_android = { value = "$ndk_bin_path/llvm-ar", force = true }

CC_armv7_linux_androideabi = { value = "$ndk_bin_path/armv7a-linux-androideabi$ANDROID_MIN_SDK-clang", force = true }
CXX_armv7_linux_androideabi = { value = "$ndk_bin_path/armv7a-linux-androideabi$ANDROID_MIN_SDK-clang++", force = true }
AR_armv7_linux_androideabi = { value = "$ndk_bin_path/llvm-ar", force = true }

CC_i686_linux_android = { value = "$ndk_bin_path/i686-linux-android$ANDROID_MIN_SDK-clang", force = true }
CXX_i686_linux_android = { value = "$ndk_bin_path/i686-linux-android$ANDROID_MIN_SDK-clang++", force = true }
AR_i686_linux_android = { value = "$ndk_bin_path/llvm-ar", force = true }

CC_x86_64_linux_android = { value = "$ndk_bin_path/x86_64-linux-android$ANDROID_MIN_SDK-clang", force = true }
CXX_x86_64_linux_android = { value = "$ndk_bin_path/x86_64-linux-android$ANDROID_MIN_SDK-clang++", force = true }
AR_x86_64_linux_android = { value = "$ndk_bin_path/llvm-ar", force = true }
EOF

cat > "$local_properties_path" <<EOF
## This file is autogenerated by scripts/generate-android-env.sh.
# It is local to the machine and must not be committed.
sdk.dir=$ANDROID_HOME
EOF

echo "Generated $cargo_config_path"
echo "Generated $local_properties_path"

legacy_env_path="$repo_root/.android-env"
if [[ -f "$legacy_env_path" ]]; then
  echo "Legacy file still present and unused by the current setup: $legacy_env_path"
fi
